- name: Open port 9001 on firewalld for supervisor web/XML-RPC Interface
  firewalld:
    zone: public
    port: 9001/tcp
    permanent: true
    state: enabled
  notify:
    - restart firewalld
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install supervisor
  pip:
    name: supervisor
    executable: pip3

- name: Copy supervisor configuration file
  copy:
    src: supervisord.conf
    dest: /etc/supervisor/daqling/
    
- name: Setup supervisor configuration file for DAQling
  replace:
    path: /etc/supervisor/daqling/supervisord.conf
    regexp: '\$\{DAQLING_SUPERVISOR_LOG_DIR\}'
    replace: '{{daqling_supervisor_log_dir}}'
  vars:
    daqling_supervisor_log_dir: "{{ lookup('env','DAQLING_LOG_DIR') }}/supervisor"

- name: Create daqling log folders
  file:
    path: '{{daqling_log_dir}}'
    state: directory
  file:
    path: '{{daqling_supervisor_log_dir}}'
    state: directory
  vars:
    daqling_log_dir: "{{ lookup('env','DAQLING_LOG_DIR') }}"
    daqling_supervisor_log_dir: "{{ lookup('env','DAQLING_LOG_DIR') }}/supervisor"

- name: Copy supervisor inet configuration file
  copy:
    src: inet_http_server.conf
    dest: /etc/supervisor/daqling/conf.d/
    
- name: Copy supervisor systemd service file
  copy:
    src: daqling-supervisord.service
    dest: /etc/systemd/system/
    
- name: Setup systemd service file for DAQling
  replace:
    path: /etc/systemd/system/daqling-supervisord.service
    regexp: '\$\{DAQLING_SUPERVISOR_SH\}'
    replace: '{{daqling_supervisor_sh}}'
  vars:
    daqling_supervisor_sh: "{{ lookup('env','DAQLING_SUPERVISOR_SH') }}"

- name: Enabling supervisord service
  systemd:
    name: daqling-supervisord
    enabled: yes
    daemon_reload: yes
  notify:
    - restart daqling-supervisord
