- name: Install Twiddler
  pip:
    name: supervisor_twiddler
    executable: pip3

- name: Copy twiddler gui configuration file
  copy:
    src: twiddler.conf
    dest: /etc/supervisor/daqling/conf.d/
    force: no
  notify:
    - restart daqling-supervisord

- name: add cronjob to clear 30-days-old logs from daqling log folder every day
  cron:
    name: "remove old logs"
    minute: "0"
    hour: "0"
    job: "find {{daqling_log_dir}} -type f -name '*.log' -mtime +30 -exec rm {} \\; >/dev/null 2>&1"
  vars:
    daqling_log_dir: "{{ lookup('env','DAQLING_LOG_DIR') }}"
