---
- hosts: localhost
  remote_user: "{{ lookup('env','LOGNAME') }}"
  roles:
    - web-deps
  environment:
    http_proxy: "{{ lookup('env','http_proxy') }}" 
    https_proxy: "{{ lookup('env','https_proxy') }}" 
